version: "3.9"
services:
  enfugue: # Should be exact same name as "id" field in config.json
    container_name: enfugue # Should be exact same name as "id" field in config.json
    image: ghcr.io/painebenjamin/app.enfugue.ai:0.3.3 # Try to avoid "latest" tag. As it may break configs in the future.
    restart: unless-stopped # Do not change this
    environment:
      - TZ=${TZ} # Can use any env variable. See "environment variables" section in the docs
    volumes:
      - ${APP_DATA_DIR}/data/config:/config # Always start the path with ${APP_DATA_DIR}/data/. This will put all data inside app-data/my-app/data
      - ${APP_DATA_DIR}/data/projects:/projects
    ports:
      - ${APP_PORT}:45554-45556 # Can change the port number. But the first port should be 45554
    networks:
      - tipi_main_network # That should not be changed
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu