version: "3.9"
services:
  enfugue: # Should be exact same name as "id" field in config.json
    container_name: enfugue # Should be exact same name as "id" field in config.json
    image: ghcr.io/painebenjamin/app.enfugue.ai:0.3.3 # Try to avoid "latest" tag. As it may break configs in the future.
    restart: unless-stopped # Do not change this
    environment:
      - TZ=${TZ} # Can use any env variable. See "environment variables" section in the docs
      - ENFUGUE_SERVER_HOST=0.0.0.0
      - ENFUGUE_SERVER_PORT=45554
      - ENFUGUE_SERVER_DOMAIN=enfugue.${LOCAL_DOMAIN}
      - ENFUGUE_SERVER_SECURE=True             # Optional
    #volumes:
    #  - ${APP_DATA_DIR}/data/opt:/opt/enfugue # Always start the path with ${APP_DATA_DIR}/data/. This will put all data inside app-data/my-app/data
    ports:
      - 45554:45554
      - 45555:45555
      - 45556:45556    
    networks:
      - tipi_main_network # That should not be changed
    command: ["run"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu      
                